- Cargo.toml
The main [Bevy](https://github.com/bevyengine/bevy) repository uses the "-dev" suffix in the version number when working on the unreleased version. I suggest we adopt this practice so people can tell the difference between the released and unstable versions.
When 0.1.0 of this crate is released, we'll temporarily set it to "0.1.0" before upgrading it to "0.2.0-dev" afterwards.
> Change version to 0.1.0-dev

- Cargo.toml
```
$ cargo run
error: `cargo run` could not determine which binary to run. Use the `--bin` option to specify a binary, or the `default-run` manifest key.
available binaries: bevy, bevy_lint_driver
```
Configure the `default-run` manifest option
> Configure default binary

- bevy_lint/src/driver.rs
- src/lint_driver.rs
> Return `ExitCode` from `driver::main()`

- bevy_lint/Cargo.toml
- rust-toolchain.toml
Fixes #19, please see the issue description for motivation!
I chose [this commit](https://github.com/rust-lang/rust-clippy/tree/e8ac4ea4187498052849531b86114a1eec5314a1/clippy_utils) because it was the most recent and actually compiled with the configured nightly. We may need to fidget with this version in the future if we encounter any issues with it.
> Add `clippy_utils` as a dependency to `bevy_lint`

- README.md
- rust-toolchain.toml
I got bit by this when trying to build the CLI for the first time. Apparently, there's [a bug](https://github.com/rust-lang/rustup/issues/3255) in `rustup` that causes components to not be installed when nightly is selected. Fortunately, installing them manually works just fine, so I added instructions for it to the README.
> chore: update README to include instructions to manually install rustc components

- README.md
- rust-toolchain.toml
I caught a few things after #28 was merged, so this implements them. I modified the component installation command to target the specific nightly version that we have pinned, since that should be the only toolchain that should matter.
> Small changes to manual component installation instructions

- bevy_lint/src/bin/main.rs
This passes all arguments from `bevy_lint` to `cargo check`, which let's to specify what should be checked and how.
For example, you can now run `bevy lint --workspace` or `bevy lint --example foo`.
> Forward arguments from `bevy lint` to `cargo check`

- src/external_cli/arg_builder.rs
- src/external_cli/mod.rs
- src/lib.rs
With the `bevy build` and `bevy run` commands, we need to work quite a lot with external CLI tools.
We often need to pass flags or options conditionally or add arguments with a value, which is a lot easier with these utilities.
See #24 for more context.
> Add ArgBuilder utility to make it easier to construct command arguments

- Cargo.lock
- Cargo.toml
- src/external_cli/mod.rs
- src/external_cli/rustup.rs
- src/lib.rs
For targeting the web, the user might need to install the WASM targets.
This PR adds utilities to make this easier
> Add wrapper for rustup command

- Cargo.lock
[Dependabot notified us about a security issue with `gix-path`.](https://github.com/TheBevyFlock/bevy_cli/security/dependabot/1) ([CVE](https://github.com/advisories/GHSA-m8rp-vv92-46c7)) We depend on `gix-path` indirectly, through `cargo-generate`. (Which you can see by running `cargo tree -i gix-path`.)
To fix this, I just ran `cargo update` to get `gix-path@v0.10.11`. The crates updated, for reference:
```
cargo update
Updating crates.io index
Updating git repository `https://github.com/rust-lang/rust-clippy`
Locking 21 packages to latest compatible versions
Updating anyhow v1.0.86 -> v1.0.88
Updating cc v1.1.15 -> v1.1.18
Updating clap v4.5.16 -> v4.5.17
Updating clap_builder v4.5.15 -> v4.5.17
Updating cpufeatures v0.2.13 -> v0.2.14
Updating gix-path v0.10.10 -> v0.10.11
Updating …
```
> Bump `gix-path`

- Cargo.lock
- Cargo.toml
- src/template.rs
> Use bevy_new template

- Cargo.lock
- Cargo.toml
- src/bin/main.rs
- src/template.rs
This:
So the following are all valid:
```shell
bevy new foo
bevy new foo -t 2d
bevy new foo -t someorg/somerepo
```
Obviously, this is a rather simplistic solution! However, in the absence of a larger library of templates, perhaps YAGNI should be the rule?
> Allow 2d as a template value for quickstart

- Cargo.lock
- bevy_lint/Cargo.toml
- bevy_lint/src/callback.rs
- bevy_lint/src/lib.rs
- bevy_lint/src/lints/main_return_without_appexit.rs
- bevy_lint/src/lints/mod.rs
- bevy_lint/src/paths.rs
This is the first lint! Closes #53. Please see the module documentation or [this link](https://hackmd.io/4ciCsSb7SxyqnteFzirEDA?view#main_return_without_appexit) for information about what the lint does.
- Lint modules are there documentation, and as such are public.
- `lints/mod.rs` has the `LINTS` static for `register_passes()` function, so you don't have to remember to touch `BevyLintCallback` each time you add a lint.
- For now, lints are going to be manually added as modules, to `LINTS`, and to `register_passes()`. I tried using a macro, but it was too complicated and not worth it.
- Lints should be declared with the builtin `declare_tool_lint!` and `declare_lint_pass!` macros.
- This lint does not detect if you emit `AppExit` through some other means, such as:
```rust
fn main() { …
```
> Add lint: `bevy::main_return_without_appexit`

- src/external_cli/mod.rs
- src/external_cli/wasm_bindgen.rs
Further work towards #24 
`wasm_bindgen` is used to generate JS bindings for the WASM executable.
> Add wrapper for wasm_bindgen CLI

- src/external_cli/cargo/build.rs
- src/external_cli/cargo/mod.rs
- src/external_cli/mod.rs
Further work towards #24.
This PR adds wrappers to call `cargo build`.
Note that we are redefining (almost) all arguments that can be passed to `cargo build`.
This may be quite verbose, but it allows us to output a useful help message for `bevy build` as well as using some of the cargo arguments for our own customization. For example, we need access to the `--target` and `--release`  arguments.
> Add wrapper for cargo build command

- bevy_lint/src/bin/main.rs
The code is pretty self-explanatory! Now, if `cargo` fails with exit code 101, so will `bevy_lint`.
> Return `cargo`'s exit code on failure in `bevy_lint`

- bevy_lint/src/callback.rs
- bevy_lint/src/groups.rs
- bevy_lint/src/lib.rs
- bevy_lint/src/lint.rs
- bevy_lint/src/lints/insert_event_resource.rs
- bevy_lint/src/lints/main_return_without_appexit.rs
- bevy_lint/src/lints/mod.rs
Closes #90.
This PR implements lint groups! These, just like Clippy's groups, allow enabling and disable multiple lints at a time based on their categories. I, stealing Clippy's groups, have added:
- Correctness: Zero-false-positives deny-by-default "if you hit these, you're wrong" lints
- Suspicious: Like Correctness, but the behavior causing the lint may actually be intended. These are warnings, not hard errors.
- Complexity: Hey, you! That `while` you wrote there could be a `for `loop! (This category checks for overly-complex code with good alternatives.)
- Performance: Anything that can be changed to improve performance. (No, this doesn't warn if you call `std::thread::sleep()`, that's your own fault.)
- Style: By far the most controversial of them all, this category enforces …
> Create lint groups

- bevy_lint/src/callback.rs
- bevy_lint/src/groups.rs
- bevy_lint/src/lib.rs
- bevy_lint/src/lint.rs
- bevy_lint/src/lints/mod.rs
Looks like I forgot to register the lint groups introduced in #98. Whoops!
While I'm at it, I also changed the visibility of some items so that less is public that before.
> Actually *register* the lint groups

- Cargo.lock
- Cargo.toml
- src/external_cli/cargo/metadata.rs
- src/external_cli/cargo/mod.rs
The `cargo metadata` command outputs a lot of useful information about the current package.
This will be helpful for the `build`, `run` and `bump` commands.
See the [`cargo metadata` documentation](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html) for more info.
Note that with this PR, we don't support the full output yet, we can incrementally add more things as we need them.
> Add basic support for cargo metadata

- src/external_cli/cargo/mod.rs
- src/external_cli/cargo/run.rs
Similar to #76, but for `cargo run`.
It gives us access to all the `cargo run` arguments and allows us to add them to our `bevy run` help command.
See #24 for context.
Usage: `cargo::run::command()`
> Add a wrapper for cargo run

- src/external_cli/arg_builder.rs
> Handle empty value lists for `ArgBuilder::add_value_list`

- Cargo.lock
- Cargo.toml
- src/bin/main.rs
- src/build/args.rs
- src/build/mod.rs
- src/external_cli/cargo/install.rs
- src/external_cli/cargo/metadata.rs
- src/external_cli/cargo/mod.rs
- src/external_cli/mod.rs
- src/external_cli/rustup.rs
- src/external_cli/wasm_bindgen.rs
- src/lib.rs
- src/manifest.rs
This PR adds the remaining pieces needed for the `bevy build` command.
The command is a wrapper around `cargo build`, but with an additional `web` sub command which makes it a lot easier to build an app for the browser.
I also plan to add additional features in the feature, like #68.
The PR contains the following changes:
- Added `cargo install` wrapper to install a program if it's missing (prompting the user).
- Added helper to obtain the current package name via `Cargo.toml`. There are likely better ways to do this (perhaps via `cargo metadata`), but I already had this implemented and we can improve it in a follow-up if needed.
- Added helper to determine the active compilation profile, which is needed to determine the path to the build artifact.
- Implemented the build command itself. …
> Bevy build

- .github/workflows/ci.yml
- Cargo.lock
- README.md
- bevy_lint/Cargo.toml
- bevy_lint/build.rs
- bevy_lint/src/bin/main.rs
- rust-toolchain.toml
- src/external_cli/cargo/run.rs
This PR tackles a few issues with how `bevy_lint` functions.
First, it closes #117 by passing `--cfg bevy_lint` to `rustc` when `bevy_lint` is called. This allows code to conditionally configure lints (e.g. `#[cfg_attr(bevy_lint, allow(bevy::lint))]`).
Secondly, it fixes #118 by specifying the nightly version when calling `cargo check`. I originally hardcoded this version, but after a comment from @richchurcher I adjusted it to take the version from `rust-toolchain.toml`. (It specifically uses a build script to parse `rust-toolchain.toml` using `toml_edit`, then passes it to the code using an environmental variable.)
Thirdly, I removed other hard-coded references to the specifically nightly channel in `README.md` and `ci.yml`. (In CI I specifically used [Taplo](https://taplo.tamasfe.dev) …
> Bug fixing and chores related to linting

- bevy_lint/src/bin/driver.rs
This makes the `bevy_lint_driver` binary behave a bit more like `clippy-driver`, which means it also behaves a bit more like `rustc`. Some changes include:
- Panicking will now result in an ICE, which can be used to debug issues.
- Logging is now setup, so you can set the `RUSTC_LOG` variable to configure logging levels and scope. (It uses `tracing` internally!)
- Exit code logic now mirrors the functionality recommended for `rustc` drivers: specifically using `catch_with_exit_code()`.
~~I'm currently debugging an issue with this where `serde_derive` fails to compile (I believe it's the `rustc_driver::args::raw_args()` call), so I'll update this when I fix it. :)~~
> Improve lint driver entrypoint

- bevy_lint/src/lib.rs
- bevy_lint/src/lints/insert_event_resource.rs
Fixes #114!
The migrates `bevy::insert_event_resource` from using the quasi-deprecated [`lower_ty()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_analysis/fn.lower_ty.html) function to [`TypeckResults::node_type()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/typeck_results/struct.TypeckResults.html#method.node_type). The behavior of the lint should not change, though this PR may fix a few hidden crashes.
> Replace `lower_ty()` with `typeck_results.node_type()`

- bevy_lint/src/lib.rs
`rustc` has a series of [internal lints](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/internal/index.html) that checks that its own APIs are being used correctly. Since we are using private `rustc` crates, we should enable these lints to avoid footguns.
I first learned about this lint group when browsing Clippy's source code. Funnily enough, `rustc -W help` doesn't print `internal` as a possible group, which is why I didn't know about it earlier.
> Warn on `rustc::internal` lints

- .github/workflows/ci.yml
- src/external_cli/cargo/metadata.rs
[Typos](https://github.com/crate-ci/typos) is a spell checker that is used in both Bevy's engine and website CI. This PR sets up Typos to be run during CI, checking commits and pull requests, since @TimJentzsch may not always be there to catch my spelling mistakes!
> Setup Typos in CI

- bevy_lint/src/lints/missing_reflect.rs
Fixes #148.
The `missing_reflect` lint crashed when checking `bevy_reflect` due to incorrect assumptions about the orphan rule.
When searching for types that implement certain traits, `Reflect` in this case, `missing_reflect`:
1. Finds all local trait `impl` blocks within a specific crate.
2. Filters them for `impl Reflect for T` blocks.
4. Looks up the [`Node`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/hir/enum.Node.html) for `T` in the local crate, returning it in an iterator.
While that is a greatly simplified version of what `TraitType::from_local_crate()` does, it conveys enough to understand where things went wrong.
In order to find the final `Node` for `T`, the lint pass calls [`TyCtxt::hir_node()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/cont …
> Fix ICE when checking `bevy_reflect`

- bevy_lint/src/callback.rs
- bevy_lint/src/groups.rs
- bevy_lint/src/lib.rs
- bevy_lint/src/lint.rs
- bevy_lint/src/lints/insert_event_resource.rs
- bevy_lint/src/lints/mod.rs
This PR:
1. Adds documentation to all public items. (Crate-level docs, module-level docs, other public items.)
2. Adds the `declare_group! {}` macro to automatically document the name and default level of lint groups.
3. Improves the `declare_bevy_lint! {}` macro to auto-document lint name, group, and description. (Closes #112.) I unfortunately could only add this to the `LINT_NAME` static and not the module-level docs, but it's better than looking through the source code.
4. ~~Made `bevy::insert_event_resource` a Correctness lint instead of Suspicious, making it deny-by-default. The only time the lint is a false positive is within `App::add_event()`, since it must internally call `init_resource::<Events<T>>()`.~~ Edit: reverted due to …
> Lint documentation improvements

- src/build/mod.rs
- src/external_cli/cargo/metadata.rs
- src/run/mod.rs
`bevy run web` quickly stopped working for more complex repository setups, because it couldn't figure out which package it had to run.
This PR adds a more sophisticated detection of the binary package detection.
We first take a look at the `--bin` and `--package` args.
If they are not defined, we try to determine the package automatically with the information provided by `cargo metadata`. We first look for the `default_run` definition and otherwise check if there is only a single binary package that could be run.
You can test this with the setup in <https://github.com/TimJentzsch/bevy_complex_repo>.
To do that, first install the Bevy CLI on this branch with `cargo install --path .`, then use `bevy run web` or `bevy run web -p cplx_demo` on that repository in the `app` folder.
> Improve binary package detection for `bevy run`

- bevy_lint/src/lints/panicking_methods.rs
- bevy_lint/tests/ui/panicking_methods/world.rs
- bevy_lint/tests/ui/panicking_methods/world.stderr
Closes #129.
I missed [`World::run_schedule()`](https://docs.rs/bevy_ecs/0.14.2/bevy_ecs/world/struct.World.html#method.run_schedule) in my first pass over all panicking `World` methods. This fixes that, and suggests `try_run_schedule()` instead.
> Support `run_schedule()` in `panicking_world_methods` lint

- .vscode/settings.json
This change lets contributors using VSCode to press `Ctrl + T` to search for dependency types (including `rustc`!), not just local crate types. (For example, try searching for `TyCtxt`!)
I believe this is an ergonomic improvement, but it can clutter up and slow down the search results. Let me know if you don't think this is an improvement!
Originally found while browsing [Kani's section on working with `rustc`](https://model-checking.github.io/kani/rustc-hacks.html#vscode).
> Enable fuzzy-searching for dependency crates in VSCode

- Cargo.lock
- bevy_lint/CHANGELOG.md
- bevy_lint/Cargo.toml
- bevy_lint/docs/release.md
This PR lays down the framework for `bevy_lint`'s release process.
- It creates a release checklist, inspired by [the engine's release checklist](https://bevyengine.org/learn/contribute/project-information/release-process/), for publishing a new version of `bevy_lint`.
- It creates a changelog that allow users to refer to changes between versions, based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/). Large user-facing changes should be documented here with each PR.
<details>
<summary>Old argument on switching to 0.0.1, convinced otherwise and reverted</summary>
- Set `bevy_lint`'s version to `0.0.1-dev` instead of `0.1.0-dev`. This is mainly because:
- `bevy_lint` will never be stable as long as `bevy` isn't stable, which means no 1.0 for now.
- We cannot publish to …
> Write `bevy_lint` release checklist and changelog

- bevy_lint/README.md
- bevy_lint/docs/release.md
Closes #165, begins tackling #109.
This PR makes some small improvements to `release.md` based on @MrGVSV's comments. It also adds a minimal `README.md` with the compatibility table.
This `README.md` is not in its the final form, and it will be significantly improved once #109 and #161 are done.
> Clarify `release.md` and add compatibility table

- bevy_lint/README.md
- bevy_lint/docs/release.md
- bevy_lint/src/lib.rs
- rust-toolchain.toml
Originally part of #152, closes #109.
This fills out the `README.md` for `bevy_lint`, including installation intructions and a guide on usage. This is the [final blocker to release 0.1.0](https://github.com/TheBevyFlock/bevy_cli/milestone/1), which is exciting!
I tried to split this up into small, incremental commits, so you may have an easier time [reviewing it like that](https://github.com/TheBevyFlock/bevy_cli/pull/170/commits). You can build the `rustdoc` version of the `README.md` by calling `cargo doc-lints`.
> Add `README.md` for `bevy_lint`

- bevy_lint/src/lib.rs
- bevy_lint/src/lints/mod.rs
- bevy_lint/src/lints/zst_query.rs
- bevy_lint/src/utils/hir_parse.rs
- bevy_lint/src/utils/mod.rs
- bevy_lint/tests/ui/zst_query/query.rs
- bevy_lint/tests/ui/zst_query/query.stderr
> bevy_lint: Add `zst_query` lint

- Cargo.lock
- bevy_lint/CHANGELOG.md
- bevy_lint/Cargo.toml
- bevy_lint/README.md
- bevy_lint/docs/index.md
- bevy_lint/src/groups.rs
- bevy_lint/src/lint.rs
- bevy_lint/src/lints/mod.rs
- rust-toolchain.toml
As per [the release checklist](https://github.com/TheBevyFlock/bevy_cli/blob/ff952b226f33615f989dec9e0432df3e89606313/bevy_lint/docs/release.md), this PR kicks off the release for `bevy_lint` v0.1.0. Now is the time to assess its current features, review any outstanding changes or bugs, and run tests on real-world projects.
Once this pull request is approved by at least one core Bevy maintainer, I will merge it and create the Github release, then open a post-release PR setting up for v0.2.0-dev. Between the time this is merged and the post-release PR is merged there will be a feature freeze, preventing all other PRs related to `bevy_lint` from being merged. While I would appreciate freezing `bevy_cli` PRs as well for aesthetic reasons, it's not a requirement. :)
> Release `bevy_lint` v0.1.0

- Cargo.lock
- bevy_lint/CHANGELOG.md
- bevy_lint/Cargo.toml
- bevy_lint/README.md
- bevy_lint/docs/release.md
This, following the [release checklist](https://github.com/TheBevyFlock/bevy_cli/blob/663298e1e24a6422abd001b6142dc53f371c3bcd/bevy_lint/docs/release.md), updates `bevy_lint` to v0.2.0-dev. I also added some missing information to the release checklist, based off of my experience releasing v0.1.0.
Once this is merged, the feature freeze will be lifted, letting #164 and #173 be merged.
> v0.1.0 post-release

- .github/workflows/docs.yml
This is a change I forgot to add in #161. It fixes the alerts so instead of looking like:
They look like:
While this fix is not necessary for v0.1.0's release, I would like to get it in sooner rather than later! :)
> Use `cargo doc-lints` when building Github Pages

- bevy_lint/docs/tutorials/editor.md
The neovim part is a bit flexible for a tutorial maybe better as a howto (bikeshedding) regardless I think this should be enough to get people started and not wondering why they don't get LSP hints
> feat: add neovim section to the editor tutorial

- Cargo.lock
- Cargo.toml
- src/build/args.rs
- src/build/mod.rs
- src/lib.rs
- src/run/args.rs
- src/run/mod.rs
- src/web/mod.rs
- src/web/wasm_opt.rs
Closes #196, unblocks <https://github.com/TheBevyFlock/bevy_new_2d/pull/312>.
With `wasm-opt`, we can further increase the performance and reduce the file size of the Wasm binary we use for web builds.
This speeds ups the app both in-game and the loading times.
As a simple first solution, we add a hard-coded size optimization pass in release mode.
In future PRs, we can make this more configurable.
To the user, we log the time the optimization took as well as the file size reduction as percentage.
This is behind the `wasm-opt` feature flag (currently disabled by default), to give the user a way to turn this off and because this increases compile times of the CLI quite a bit.
> Optimize binary with `wasm-opt` in release mode

- src/build/args.rs
- src/build/mod.rs
- src/external_cli/cargo/install.rs
- src/external_cli/rustup.rs
- src/run/args.rs
- src/run/mod.rs
Closes #203 
Add a `--yes` flag to `bevy run` and `bevy build`.
Pass the flag to `bevy_cli::external_cli::cargo::install` and `bevy_cli::external_cli::rustup::install_target_if_needed`
> Add --yes argument to confirm all prompts automatically

- src/build/mod.rs
- src/external_cli/cargo/install.rs
- src/external_cli/wasm_bindgen.rs
> Install the exact `wasm-bindgen-cli` version matching the `wasm-bindgen` version

- Cargo.lock
- bevy_lint/Cargo.toml
- bevy_lint/README.md
- bevy_lint/src/paths.rs
- bevy_lint/tests/ui/missing_reflect/impl.rs
- bevy_lint/tests/ui/missing_reflect/impl.stderr
- bevy_lint/tests/ui/missing_reflect/impl_ref.rs
- bevy_lint/tests/ui/missing_reflect/impl_ref.stderr
- bevy_lint/tests/ui/panicking_methods/world.rs
- bevy_lint/tests/ui/panicking_methods/world.stderr
This updates the linter to support Bevy 0.15. As #138 has not yet been implemented, Bevy 0.14 support is being dropped.[^0]
Overall, it was surprisingly simple. I bumped the version of Bevy we use in testing, then fixed any errors. The UI tests are so rigid that even the slightest quiver could cause them to fail, which in this case is a good thing!
The one thing of note is that I'm keeping support for `World::many_entities()` and `many_entities_mut()` in `bevy::panicking_world_methods` even though they are deprecated. Since `panicking_methods` is likely a lint that would be denied in projects, I don't want panicking methods to slip by just because someone added `#[allow(deprecated)]` while migration their project. Once these methods are completely removed from Bevy, we'll remove them from …
> Linter: Support Bevy 0.15

- Cargo.lock
- bevy_lint/Cargo.toml
- bevy_lint/README.md
- bevy_lint/docs/README.md
- bevy_lint/docs/how-to/bump-rust.md
- bevy_lint/src/bin/driver.rs
- rust-toolchain.toml
Rust 1.84 has been released, meaning it's time to bump our Rust toolchain and `clippy_utils`! Additionally, I've written some documentation on how to do this so that others can follow the same steps.
> Bump linter to `nightly-2025-01-09`

- src/external_cli/cargo/mod.rs
- src/run/mod.rs
Closes #218.
For some reason, the profile `dev` has a target folder named `debug` instead of `dev`.
This caused a compile error on native dev builds.
- Extract the artifact folder path logic into a separate function
- Add a special case for the `dev` profile
- Add some unit tests
Run `bevy build` on a Bevy project, using this branch for the Bevy CLI.
It shouldn't fail with an error.
We should probably set up some more tests for the CLI, testing all the build and run commands and potentially different targets and profiles.
But that would require non-trivial setup work, so I will defer it for a future task.
> Fix determining artifact folder for dev profile

- bevy_lint/src/lint.rs
- src/lint.rs
Now when you run `bevy lint` (from the CLI) and the linter is _not_ installed, it will recommend installing it from [the website](https://thebevyflock.github.io/bevy_cli/bevy_lint/), not Github.
Additionally, it looks like I accidentally commented out `#[doc(hidden)]` on `declare_bevy_lint!` in #216, so this fixes that too.
> Update linter install link and fix `declare_bevy_lint!` visibility

- README.md
Closes #204.
It's currently hard for users to discover how to use the web-specific functionality of the CLI.
As a first step, we should expand the README to give an overview of the provided features.
- Add installation instructions
- Add an overview of the main features and configuration options
> Add documentation for web commands to README

- src/bin/main.rs
- src/build/mod.rs
- src/external_cli/cargo/mod.rs
- src/external_cli/cargo/run.rs
- src/run/args.rs
- src/run/mod.rs
- src/web/bundle.rs
Closes #229.
The `bevy run web` command cannot just wrap `cargo run`, as we don't want to run a native application, but run the code in the user's browser.
Hence, we have to manually build with `cargo build` instead.
This causes quite a lot of code (also including calling `wasm-bindgen`) to be duplicated between `bevy build web` and `bevy run web`.
To ensure consistency and aid development, the code should be shared where possible.
This will enable us to build more complex features like #226.
- Extract reusable part of `bevy build web` into dedicated function.
- Add a conversion from run args to build args.
- Call the `bevy build web` logic in `bevy run web` as well.
The functionality _should_ be equivalent.
In the future, we might refine how exactly the shared build function is called. …
> De-duplicate web build code

- bevy_lint/src/lib.rs
- bevy_lint/src/lint.rs
- bevy_lint/src/lints/borrowed_reborrowable.rs
- bevy_lint/src/lints/insert_event_resource.rs
- bevy_lint/src/lints/main_return_without_appexit.rs
- bevy_lint/src/lints/missing_reflect.rs
- bevy_lint/src/lints/mod.rs
- bevy_lint/src/lints/panicking_methods.rs
- bevy_lint/src/lints/plugin_not_ending_in_plugin.rs
- bevy_lint/src/lints/zst_query.rs
Often lints need to compare [`Symbol`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/symbol/struct.Symbol.html)s. Some lints take the inefficient route by interning the string each time:
```rust
if ident.name == Symbol::intern("component") {
// ...
}
// Also seen as...
if ident.name == sym!(component) {
// ...
}
```
This is bad because interning a string is quite expensive. To avoid this, lint passes cache the `Symbol`:
```rust
struct MyLintPass {
component_sym: Symbol,
}
impl Default for MyLintPass {
fn default() -> Self {
Self { component_sym: Symbol::intern("component") }
}
}
impl<'tcx> LateLintPass<'tcx> for MyLintPass {
fn check_expr(&mut self, cx: &LateContext<'tcx>, expr: &Expr<'tcx>) {
// ...
if ident.name == self.component_sym {
// ...
}
}
}
```
This requires a lot …
> Extend `declare_lint_pass!` macro

- src/external_cli/cargo/install.rs
- src/external_cli/rustup.rs
Closes #212.
We are showing interactive prompts before we install any required tooling.
In non-interactive shells (e.g. CI), this will fail with an error.
We should improve this error message to guide the user towards the `--yes` flag, which confirms the prompts automatically.
Use `anyhow`'s `.context(...)` to make the error message more useful, guiding the user towards `--yes`.
Tested in one of [testing repositories in CI](https://github.com/TimJentzsch/bevy_complex_repo/actions/runs/12867761889/job/35873080585?pr=1#step:6:9).
New output:
```txt
Error: failed to show interactive prompt, try using `--yes` to confirm automatically
Caused by:
0: IO error: not a terminal
1: not a terminal
Error: Process completed with exit code 1.
```
> Improve error message when showing prompt in non-interactive shell

- src/run/mod.rs
Closes https://github.com/TheBevyFlock/bevy_cli/issues/200.
Improve compile time by only compiling the default run target if available and no specific binary is omitted via the `--bin` or `--example` flags.
Check if `bevy run` was called with either `--bin` or `--example`. If not search for the default_run binary name and append it with `--bin` before calling `build_web(&mut build_args)`
*Before:*
```
bevy_complex_repo/app
❯ cargo clean
Removed 2378 files, 2.6GiB total
bevy_complex_repo/app
❯ bevy run web
Compiling to WebAssembly...
Compiling cplx_core v0.1.0 
Compiling cplx_teaser v0.1.0
Compiling cplx v0.1.0 
Compiling cplx_demo v0.1.0 
Finished `web` profile [unoptimized + debuginfo] target(s) in 37.09s
Bundling JavaScript bindings...
```
*Now:*
```
bevy_complex_repo/app
❯ cargo clean …
```
> `bevy run web`: only compile `default_run` target when no binary is specified

- README.md
Closes #239!
The section is pretty sparse, especially because I intentionally omitted the installation instructions (they're too complicated + too likely to go out-of-date, in my opinion).
As an extra drive-by fix, I switched the `cli` code block attributes to `sh`, which fixes syntax highlighting for me in VSCode. I can revert this if it's not desired!
> Add linter section to CLI `README.md`

- assets/web/index.html
The script for restarting the audio context for web apps didn't work.
This resulted in the app not getting any audio.
The fix is simple: The script for restarting the audio context needs to be called _before_ the app is loaded, I assume to ensure that the creation of the audio context is tracked correctly.
You can test it on the current prototype of the [`bevy_new_2d` port](https://github.com/TheBevyFlock/bevy_new_2d/pull/312).
Compare `bevy run --no-default-features web --open` with the current `main` and this branch.
This branch should have sound when you click the buttons.
> Fix audio context not restarting automatically

- .github/workflows/ci.yml
Closes #254.
Should reduce CI times again by caching the workspace we use for the CLI E2E tests, so we don't have to rebuild them every time.
I opted for adding a separate cache for the test workspace instead of adding the testing package to the CLI workspace (which would then include it in the CLI cache).
That way, the Bevy dependency is not included in the caches of the other jobs and we can keep it a separate workspace, making it easier to test the workspace-related CLI arguments.
The downside is that the cache size will probably grow.
The `cargo-cache` action also doesn't have a `working-directory` input yet, so it's a bit more verbose to change that. I opened <https://github.com/Leafwing-Studios/cargo-cache/issues/44> to track this.
Let's let it run through and see if it works.
> Add cache for test workspace

- bevy_lint/src/bin/main.rs
As mentioned by @christopherbiscardi on Discord, `bevy_lint` does not yet support the `--version` flag! `--version` is useful to see what version of the linter is installed, and whether it can be updated or not.
This PR adds support for `--version` and does some minor refactors to `bevy_lint/src/bin/main.rs`.
```bash
$ cargo run -p bevy_lint -- --version
bevy_lint 0.2.0-dev
$ bevy_lint --version
bevy_lint 0.2.0-dev
```
At some point I would like to include additional information if `--verbose` is also specified, just like how Cargo does with `cargo --version --verbose`. At the very least, I would like to expose the Rust toolchain channel required (which we already have access to with `RUST_TOOLCHAIN_CHANNEL`).
> Linter: Add support for `--version` flag

- Cargo.lock
- bevy_lint/src/bin/main.rs
This updates to `openssl` v0.10.70, which fixes a use-after-free vulnerability.
https://github.com/TheBevyFlock/bevy_cli/security/dependabot/3
> Bump `openssl` and fix CI on Windows

- bevy_lint/src/lints/zst_query.rs
Due to #252, `zst_query` isn't yet ready to be out in production. This PR lowers it to the [`NURSERY`](https://thebevyflock.github.io/bevy_cli/bevy_lint/groups/static.NURSERY.html) lint group, which marks it as unstable for the time being.
> Lower `zst_query` to be a nursery lint

- src/external_cli/cargo/metadata.rs
When the a call to `cargo metadata` fails the only output the user sees is "Error: EOF while parsing a value at line 1 column 0" which doesn't explain anything. This change adds additional context.
I have made the choice to try to print stderr if it can be decoded as utf-8 because that is where I believe all the useful stuff will always be. If decoding fails I print the debug format for the Output struct which will at least have some information.
fixes: #242
> Make errors more informative when cargo metadata fails

- bevy_lint/src/bin/main.rs
- bevy_lint/src/callback.rs
The `bevy_lint` executable currently runs:
```shell
RUSTC_WORKSPACE_WRAPPER=path/to/bevy_lint_driver cargo +TOOLCHAIN check --cfg bevy_lint
```
This broke for [someone on Discord](https://discord.com/channels/691052431525675048/1278871953721262090/1337252666027540503), however, because the `+TOOLCHAIN` syntax requires [Rustup's `cargo` proxy](https://rust-lang.github.io/rustup/concepts/proxies.html), which may not be in their `PATH`. This PR fixes this by instead calling `rustup run` directly:
```shell
RUSTC_WORKSPACE_WRAPPER=path/to/bevy_lint_driver rustup run TOOLCHAIN cargo check --cfg bevy_lint
```
Both versions do the exact same thing, and both will fail if you do not have Rustup installed, but the latter version should work in a few more scenarios. (And it makes the error message …
> Don't use `cargo +TOOLCHAIN` shortcut and move `--cfg bevy_lint` logic

- bevy_lint/README.md
Closes #268. Thanks @christopherbiscardi for originally pointing out that this needed to be done!
> Add link to full list of lints in `README.md`

- bevy_lint/src/utils/cargo.rs
This removes a bit of extra logic from the Cargo utility `locate_manifest()`. Originally `locate_manifest()` was designed to work with any given `Path`, even if that path was a folder instead of a file.
Since then, `locate_manifest()` was modified in 492b0e2c120536b80efaa50b773a14ece8628854 to take an `Input` instead of a `Path`. This `Input` is guaranteed to be a file, not a folder, so the original check can be removed.
Just in case, I left a `debug_assert!()` verifying that the `Input` is a file.
> Simplify `locate_manifest()`

- Cargo.lock
- Cargo.toml
- src/bin/main.rs
`clap_complete` is a neat little crate which allows to generate shell auto-completions for `clap` based CLI projects. 
It works by running e.g. `bevy completion bash` which will print out a lot of shell code to the commandline. This is can then be used by users to manually install the autocompletions for their shell or by package managers to automatically install the completions while installing the binary.
I'm not sure about the `completion` subcommand name. Feel free to suggest anything else and I'll adapt this PR.
> Add Shell-Completion Auto-generation

- Cargo.lock
- bevy_lint/Cargo.toml
- bevy_lint/README.md
- bevy_lint/docs/README.md
- bevy_lint/docs/how-to/types.md
- bevy_lint/src/bin/driver.rs
- bevy_lint/src/bin/main.rs
- bevy_lint/src/lints/borrowed_reborrowable.rs
- bevy_lint/src/lints/insert_event_resource.rs
- bevy_lint/src/lints/main_return_without_appexit.rs
- bevy_lint/src/lints/missing_reflect.rs
- bevy_lint/src/lints/panicking_methods.rs
- bevy_lint/src/lints/plugin_not_ending_in_plugin.rs
- bevy_lint/src/lints/zst_query.rs
- bevy_lint/src/utils/hir_parse.rs
- bevy_lint/tests/ui.rs
- bevy_lint/tests/ui/insert_event_resource/main.stderr
- rust-toolchain.toml
- tests/bevy_cli_test/Cargo.lock
[Rust 1.85.0 is out](https://blog.rust-lang.org/2025/02/20/Rust-1.85.0.html)! Following [these instructions](https://github.com/TheBevyFlock/bevy_cli/blob/2668cbabca0b8dbbfec55fda1f445dbce8edc868/bevy_lint/docs/how-to/bump-rust.md), I updated [`clippy_utils`](https://crates.io/crates/clippy_utils) to the latest version: v0.1.87. I wrote down a list of notable changes in `clippy_utils` and `rustc` in ee0c7a35ee2f41c4c7e724063199acc64906ef4a, check it out!
Along with these changes, Rust 2024 is officially stable! This PR migrates the linter to 2024, though it leaves the CLI. (@TimJentzsch I can do this if you would like, but in a seperate PR preferably!)
I highly recommend reviewing each commit individually. I left extended discussion in the commit descriptions, and all of my work is nicely …
> Bump linter to `nightly-2025-02-20` and Rust 2024

- bevy_lint/src/bin/main.rs
Fixes #267! For more context, see [this comment](https://github.com/TheBevyFlock/bevy_cli/issues/267#issuecomment-2678683811):
> I found the issue! Due to [rust-lang/rustup#3703](https://github.com/rust-lang/rustup/pull/3703), Rustup no longer modifies the `PATH` on Windows because it prevented sub-invocations of `cargo` and `rustc` from going through their proxy. There was a [call for testing](https://internals.rust-lang.org/t/help-test-windows-behavior-between-rustup-and-cargo/20237) related to this, but it was announced before the linter was ever created. Because I don't use Windows frequently, I never caught the issue.
> 
> We can fix this by setting `RUSTUP_WINDOWS_PATH_ADD_BIN=1`:
> 
> ```cmd
> > set RUSTUP_WINDOWS_PATH_ADD_BIN=1
> > rustup run nightly-2025-01-09 .\bevy_lint.exe
> …
```
> Force rustup to add `rustc_driver.dll` to the `PATH`

- assets/web/index.html
- src/build/mod.rs
- src/run/mod.rs
- src/run/serve.rs
- src/web/bundle.rs
Partially related to #123.
Removes one regression from <https://github.com/TheBevyFlock/bevy_new_2d/pull/312>.
When you currently run an app with `bevy run web`, the browser tab will just be called "Bey App".
This is not very descriptive or nice, so it would be better if we could choose a better default value.
- Adjust our bundling pipeline to allow pre-processing of the `index.html` in all cases
- If not provided, add a `<title>` with the name of the binary
- E.g. `bevy_new_2d` becomes "Bevy New 2d"
As a follow-up to this PR we can also more easily apply the post-processing with the dev-only options for the dev server.
1. Install the CLI from this branch.
2. Run any Bevy project with `bevy run web`. It should show the name of the binary in the title. Try for example `bevy run …
> Automatically add a sensible title to web page

- Cargo.lock
- Cargo.toml
- README.md
- src/bin/main.rs
- src/build/mod.rs
- src/external_cli/rustup.rs
- src/run/mod.rs
- src/web/bundle.rs
- src/web/wasm_opt.rs
For features like https://github.com/TheBevyFlock/bevy_cli/issues/275 a dedicated logging crate would be helpful to implement `-v`/`--verbose`.
I opted for `tracing` instead of `log` even though it's a bit overkill for us at the moment. `tracing` seems to be the most flexible and is also mostly used in `bevy`. But I don't really have a strong opinion on this.
```sh
❯ bevy run web
2025-02-24T21:49:19.817751Z  INFO bevy_cli::build: Compiling to WebAssembly...
Finished `web` profile [unoptimized + debuginfo] target(s) in 0.11s
2025-02-24T21:49:19.970038Z  INFO bevy_cli::build: Bundling JavaScript bindings...
2025-02-24T21:49:22.969352Z  INFO bevy_cli::web::bundle: No custom `web` folder found, using defaults.
2025-02-24T21:49:22.969406Z  INFO bevy_cli::run: Open your app at …
```
> switch to `tracing`

- bevy_lint/CHANGELOG.md
- bevy_lint/MIGRATION.md
- bevy_lint/README.md
- bevy_lint/docs/how-to/release.md
- bevy_lint/src/bin/main.rs
This PR adds a new entry to the changelog for v0.2.0. I checked over every change made between 8691821292922ba3b2ea7f52eb57cd637cfd5cfb and 9292db980bcbce820826f8e1c6ad3f7ee23336be, though I may have missed something!
This PR also creates a new file, `MIGRATION.md`, which is a migration guide. It is based off of [Bevy's migration guide](https://bevyengine.org/learn/migration-guides/introduction/), and intends to help users upgrade.
Finally, I made two smaller changes / fixes that got bundled into this PR. I removed a leftover reference to `panicking_world_methods` from the `README.md`, and I changed the format for version numbers to be vX.Y.Z instead of just X.Y.Z.
> v0.2.0 changelog, migration guide, and other small changes

- Cargo.lock
- Cargo.toml
- bevy_lint/Cargo.toml
We use an outdated version of `ui_test`. This PR updates it to the latest version (v0.29.1). The changelog is [here](https://github.com/oli-obk/ui_test/blob/ef35ab91415ffefc1288902f4d679667e460a03d/CHANGELOG.md), although it appears no changes need to be made on our side.
> Bump to a newer version of `ui_test`

- Cargo.lock
- bevy_lint/CHANGELOG.md
- bevy_lint/Cargo.toml
- bevy_lint/README.md
Following the [release checklist](https://github.com/TheBevyFlock/bevy_cli/blob/b5012ec0065d9f3c0070697451b8fd2404c640e3/bevy_lint/docs/how-to/release.md#post-release), this prepares `bevy_lint` for development for the next release: v0.3.0. This PR:
1. Bumps `bevy_lint` to v0.3.0-dev
2. Adds a new row to the compatibility table in the `README.md`
3. Adds a new section to the changelog
Merging this PR will resolve the feature freeze, letting other PRs be merged as well! :)
> Post-release v0.2.0

- tests/new.rs
Closes, but does not fix, #309.
Since the `bevy new` integration tests are really flaky in CI (especially on MacOS), this PR disables them by default. They can still be run with `cargo test -- --ignored`, however.
> Ignore `bevy new` integration tests by default

- bevy_lint/src/utils/hir_parse.rs
This was a leftover TODO that I forgot to fix, whoops!
I experimented, turns out `MethodCall::receiver` only includes the `&` when the method is fully-qualified. I added a recommendation to `peel_refs()` in this case, since if you forget your lint may behave differently.
> Add note in `MethodCall::receiver` docs that it may include the reference

- bevy_lint/src/lints/pedantic/main_return_without_appexit.rs
- bevy_lint/src/lints/restriction/missing_reflect.rs
- bevy_lint/src/lints/restriction/panicking_methods.rs
- bevy_lint/src/lints/style/plugin_not_ending_in_plugin.rs
- bevy_lint/src/lints/suspicious/insert_event_resource.rs
- bevy_lint/src/lints/suspicious/insert_unit_bundle.rs
Unifies how we access the `Session`.  Noticed I sometimes used the method to access it after reading https://github.com/TheBevyFlock/bevy_cli/issues/325
> Use direct field access instead of `HasSession` trait

- .github/workflows/ci.yml
Looks like we were accidentally doing this for the `tests` job!
> Don't install Linux dependencies twice in CI

- Cargo.lock
- Cargo.toml
> CLI: Bump to `cargo-generate` v0.23.0

- Cargo.lock
This fixes several vulnerability alerts for `openssl` and `gitoxide`. See:
- https://github.com/TheBevyFlock/bevy_cli/security/dependabot/9
- https://github.com/TheBevyFlock/bevy_cli/security/dependabot/6
> Bump dependencies in lockfile

- Cargo.lock
- bevy_lint/src/lints/restriction/panicking_methods.rs
- bevy_lint/src/paths.rs
- bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/fail/Cargo.lock
- bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/pass/Cargo.lock
- bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/fail/Cargo.lock
- bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/pass/Cargo.lock
- tests/bevy_cli_test/Cargo.lock
This PR does 3 things:
1. It stops the `panicking_methods` lint from checking for `World::many_entities()` and `World::many_entities_mut()`, which were removed in Bevy 0.16.
2. It removes the check for `QueryState`, as that type no longer has any panicking methods with non-panicking alternatives.
3. It runs `cargo update` for all of our different `Cargo.lock` files, which should fix the 5 Dependabot vulnerability alerts we have. (https://github.com/TheBevyFlock/bevy_cli/security/dependabot/11 through https://github.com/TheBevyFlock/bevy_cli/security/dependabot/15)
> Cleanup `panicking_methods` lint and run `cargo update`

- src/web/serve.rs
Cleans up one unnecessary `--verbose` log
> Only log headers if any are added

- bevy_lint/README.md
This fixes an error in the compatibility table and slightly improves the lint configuration table!
> Small fixups to the `bevy_lint` README

- src/bin/main.rs
Closes #366
Adds `b` and `r` aliases for the `build` and `run` commands. `bevy -h` now prints:
```
build        Build your Bevy app [aliases: b]
run          Run your Bevy app [aliases: r]
```
I'd prefer
```
build, b     Build your Bevy app
run, r       Run your Bevy app
```
but I don't know how to do that :)
> Add aliases for `build` and `run` commands

- src/build/mod.rs
- src/config.rs
- src/run/mod.rs
The Bevy CLI config was always built for the web targets.
I added the unit test first but the issue was not even there so it passed from the start ^^ so testing is done as described here: https://github.com/TheBevyFlock/bevy_cli/issues/370#issue-3002023740 
```sh
❯ bevy build -v
DEBUG Using config CliConfig { target: None, features: [], default_features: None }
DEBUG Running: `cargo build --profile dev`
Compiling bevy_new_2d v0.1.0 (bevy_new_2d)
error: dev_native active
--> src/main.rs:5:1
|
5 | compile_error!("dev_native active");
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: could not compile `bevy_new_2d` (bin "bevy_new_2d") due to 1 previous error
Error: Command cargo exited with status code exit status: 101
```
```sh
❯ bevy build -r -v
DEBUG Using config CliConfig { target: None, …
```
> pass `args.is_web()` to `CliConfig::for_package()`

- Cargo.lock
- bevy_lint/Cargo.toml
- bevy_lint/README.md
- bevy_lint/src/lints/pedantic/borrowed_reborrowable.rs
- bevy_lint/src/utils/hir_parse.rs
- rust-toolchain.toml
- src/external_cli/cargo/metadata.rs
Another [version of `clippy_utils` has released](https://crates.io/crates/clippy_utils/0.1.88), meaning it's time to update the linter's required toolchain! Following the [process outlined in the contributor's guide](https://github.com/TheBevyFlock/bevy_cli/blob/b6d80516f6282c6b61a9fe89cbd39bb023d04d87/bevy_lint/docs/how-to/bump-rust.md), the compatibility table is now as follows:
|`bevy_lint` Version|Rust Version|Rustup Toolchain|Bevy Version|
|-|-|-|-|
|0.3.0-dev|1.88.0|`nightly-2025-04-03`|0.16|
The largest noticeable breaking change is that `TyCtxt::fn_arg_names()` now returns `&[Option<Ident>]` instead of `&[Ident]`, meaning we now need to handle the `Option`.
> Bump Rust toolchain to `nightly-2025-04-03`

- src/bin_target.rs
- src/build/args.rs
- src/build/mod.rs
- src/external_cli/cargo/install.rs
- src/external_cli/cargo/metadata.rs
- src/external_cli/cargo/mod.rs
- src/external_cli/mod.rs
- src/external_cli/rustup.rs
- src/external_cli/wasm_bindgen.rs
- src/external_cli/wasm_opt.rs
- src/lint.rs
- src/run/args.rs
- src/run/mod.rs
- src/web/build.rs
We currently check if the required programs and targets are installed _every time_ when we run the `web` commands.
This adds overhead to the command execution and also makes the logs noisier.
First try to execute the command and only perform the checks and potential fixes if the command exits with an error.
The `ensure_web_setup` function has been removed entirely.
<details>
<summary>The new version shortens the `--verbose` output</summary>
```diff
DEBUG Using config CliConfig { target: None, features: [], default_features: None }
-DEBUG Running: `rustup --version`
-DEBUG Running: `rustup target list`
-DEBUG Running: `wasm-bindgen --version`
INFO Compiling to WebAssembly...
DEBUG Running: `cargo build --config profile.web.inherits="dev" --config profile.web-release.inherits="release" …
```
> Optimistic command execution

- src/external_cli/arg_builder.rs
- src/run/args.rs
Closes #369.
Some Bevy apps also have a CLI interface that allows passing other options.
It's currently not possible to forward args to the underlying Bevy app when using `bevy run`.
With `cargo run`, you can forward options by putting them after a plain `--`.
This should also be possible for `bevy run`.
Use `[clap(last = true)]` to capture args after `--`.
Then forward them to `cargo run` by also putting them after `--`.
Note that this only works for `bevy run` and not `bevy run web`, because you can't really run a Wasm binary with additional arguments (as far as I know...)
- Install the CLI from this branch:
```
cargo install --git https://github.com/TheBevyFlock/bevy_cli --branch 369-passing-options-to-bevy-app --locked --force bevy_cli
```
- Try e.g. `bevy --verbose run -- --api …
> Allow forwarding of args to underlying program

- src/web/bundle.rs
- src/web/serve.rs
Fixes #365.
The `bevy run web --bundle` command didn't work correctly, the web server failed to serve the bundle.
- Add more logging to the bundling process
- Fix serving packed bundles by correctly serving the entire folder
Note that I'm quite new to `axum` and had to ask Chat GPT for a bit of help here.
I initially tried something like this:
```rs
router.route_service("/", ServeDir::new(path)
```
We already use this in another place of the app.
But this approach caused issues with nested folders, e.g. the `build` directory containing the WASM and JS bindings.
With this `fallback_service` approach it seems to work as expected, but if you know of a better way to do this please let me know!
- Install the CLI from this branch:
```
cargo install --git https://github.com/TheBevyFlock/bevy_cli …
```
> Fix running web app with bundle option

- Cargo.toml
- src/build/args.rs
- src/config.rs
- src/run/args.rs
Closes #364.
- Don't log if the config doesn't change the default values
- Format the logging to be in a toml syntax
New output when there are things specified in the config:
```diff
+DEBUG Using defaults from bevy_cli config:
+default_features = false
+features = ["dev"]
INFO Compiling to WebAssembly...
DEBUG Running: `cargo build --config profile.web.inherits="dev" --bin bevy_new_2d --features dev --no-default-features --profile web --target wasm32-unknown-unknown`
Finished `web` profile [optimized + debuginfo] target(s) in 0.20s
INFO Bundling JavaScript bindings...
DEBUG Running: `wasm-bindgen --no-typescript --out-name bevy_new_2d --out-dir /home/tim/dev/bevyengine/bevy_new_2d/target/wasm32-unknown-unknown/web --target web /home/tim/dev/bevyengine/bevy_new_2d/target/wasm32-unknown-unkn …
```
> Improve logging of bevy_cli config

- src/external_cli/cargo/metadata.rs
- src/external_cli/mod.rs
We always run `cargo metadata` at the start of a CLI command to obtain more information about workspace and package as well as constructing the appropriate CLI config.
If this command fails, e.g. because you're not in a cargo workspace, the output is currently very unhelpful:
```
bevy run web              
Error: Command cargo exited with status code exit status: 101
```
- Add more context to the `cargo metadata` error to hint the user what may have gone wrong
- Log the full command when it errors instead of just the program name
```
bevy-dev run web
Error: failed to obtain package metadata, are you in a cargo workspace?
Caused by:
Command `cargo metadata --format-version 1` exited with status code exit status: 101
```
- Install the CLI from this branch
- Navigate to a non-cargo directory …
> Improve error message for failed `cargo metadata`

- bevy_lint/src/lints/style/unconventional_naming.rs
This elaborates the lint documentation for `unconventional_naming` by listing what conventions are enforced, expanding the motivation section, and providing an example for plugins.
Since `unconventional_naming` will likely be one of the most impactful lints, it's going to be under a lot of scrutiny. In order to avoid excessive bikeshedding and confusion, we should have a rock-solid description of what the conventions are and why we have them.
> Improve the docs for `unconventional_naming`

- bevy_lint/src/lints/style/mod.rs
`LintStore::register_renamed()` provides an easy method for migrating from `plugin_not_ending_in_plugin` to `unconventional_naming`. If the linter ever runs into code referencing `plugin_not_ending_in_plugin`:
```rust
#![warn(bevy::plugin_not_ending_in_plugin)]
```
It will now emit a warning that the lint has been renamed, but still correctly configure `unconventional_naming`:
```sh
warning: lint `bevy::plugin_not_ending_in_plugin` has been renamed to `bevy::unconventional_naming`
--> bevy_lint/examples/lint_example.rs:3:9
|
3 | #![warn(bevy::plugin_not_ending_in_plugin)]
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use the new name: `bevy::unconventional_naming`
|
= note: `#[warn(renamed_and_removed_lints)]` on by default
```
Since all of `plugin_not_ending_in_plugin` was merged …
> Mark `plugin_not_ending_in_plugin` as a renamed lint

- Cargo.lock
- bevy_lint/Cargo.toml
Updated our dev dependencies, most importantly changed from the rc.2 to "0.16.0" from bevy
> Linter: Update dev dependencies

- .github/workflows/ci.yml
- .github/workflows/docs.yml
This is an experiment to see if this cache action performs better than `Leafwing-Studios/cargo-cache`, just like https://github.com/TheBevyFlock/bevy_new_2d/pull/381. If this gets merged we can test it for a few weeks then evaluate whether it's an improvement or not.
Closes #400.
> Switch to `Swatinem/rust-cache`

- src/bin/main.rs
- src/build/args.rs
- src/build/mod.rs
- src/config.rs
- src/external_cli/arg_builder.rs
- src/external_cli/mod.rs
- src/lib.rs
- src/lint.rs
- src/run/mod.rs
- src/template.rs
It got discussed in the [CLI working-group ](https://discord.com/channels/691052431525675048/1278871953721262090/1364297693182300312) that the Bevy editor also uses the CLI as a library. To make it easier for them, we should "stabilize" our public interface for `0.1.0` and add some short comments on the public types.
> Document all public items of the CLI

- Cargo.lock
- Cargo.toml
- src/bin/main.rs
- src/build/args.rs
- src/external_cli/mod.rs
- src/external_cli/rustup.rs
- src/external_cli/wasm_opt.rs
- src/run/args.rs
- src/web/build.rs
- src/web/bundle.rs
- src/web/run.rs
- src/web/serve.rs
Closes #360.
Where possible, we should provide a familiar experience to users, matching what they are used to from `cargo`.
Our log message format currently looks quite different.
Use a custom formatter for `tracing` logging.
- Use lower-case log levels with a colon
- Adjust log messages to start with a lowercase letter, similar to what cargo does
Some of our messages are part of the build process and will be adjusted to look closer to the `Finished` messages `cargo` generates. See #362.
> Align logging to match `cargo`'s style

- README.md
- src/config.rs
closes #407 
Cargo.toml:
```toml
[package.metadata.bevy_cli.web.dev]
default-features = false
features = ["dev"]
```
output:
```sh
❯ bevy run web -v
debug: using defaults from bevy_cli config:
features = ["dev"]
default-features = false
rustflags = ["--cfg", 'getrandom_backend="wasm_js"']
```
> Rename `default_features` to `default-features`

- README.md
In preparation for a v0.1.0 release of the CLI, we need to improve the documentation.
This is a first pass to make the README more useful.
1. **Improved installation instructions**: Now also include easy copy & paste instructions on how to install the linter. I know this is annoying to maintain, as we need to manually update the toolchain and version number when they change. But I think it's well worth it to make the setup as easily as possible for the user.
2. **Quick start guide**: Simple commands to copy & paste to get introduced to all main CLI commands.
3. **Improved structure**: The sections are now ordered in the way you would use the CLI: You create a new project, check its code quality while developing and then run it in the browser.
> Improve README, pass 1

- src/bin/main.rs
- src/external_cli/cargo/install.rs
- src/external_cli/mod.rs
- src/external_cli/rustup.rs
- src/external_cli/wasm_bindgen.rs
- src/external_cli/wasm_opt.rs
- src/lint.rs
Allows installing `bevy_lint` `lint-v0.3.0`.
**`bevy_lint` is already installed**
<details>
```sh
❯ bevy lint -v
debug: running: `bevy_lint`
warning: unconventional type name for a `SystemSet`
--> src/lib.rs:61:6
|
61 | enum AppSet {
|      ^^^^^^ help: rename `AppSet`: `AppSystems`
|
note: structures that implement `SystemSet` should end in `Systems`
--> src/lib.rs:61:6
|
61 | enum AppSet {
|      ^^^^^^
note: `SystemSet` implemented here
--> src/lib.rs:60:10
|
60 | #[derive(SystemSet, Debug, Clone, Copy, Eq, PartialEq, Hash, PartialOrd, Ord)]
|          ^^^^^^^^^
= note: `#[warn(bevy::unconventional_naming)]` on by default
= note: this warning originates in the derive macro `SystemSet` (in Nightly builds, run with -Z macro-backtrace for more info)
warning: `bevy_new_2d` (lib) generated …
```
> Support installing `bevy_lint` via CLI

- src/web/bundle.rs
- src/web/serve.rs
Fixes #421.
If you provided a custom web folder with more than just `index.html`, it wasn't served correctly by the local web server.
Always include the custom web folder as a fall-back.
Install the CLI from this branch:
```sh
cargo install --git https://github.com/TheBevyFlock/bevy_cli --branch 421-fix-custom-web-folders --locked bevy_cli
```
Then use `bevy run web` on a project with a custom web folder, including other files in that folder. Check that these files are served correctly.
You can also test `bevy run web --bundle`, but that was already working for me on latest `main`.
> Fix serving of custom web folders

- .github/workflows/docs.yml
- docs/book.toml
CI [failed to build the docs](https://github.com/TheBevyFlock/bevy_cli/actions/runs/15098836218/job/42437102756) because I misspelled "linkcheck" for "lintcheck". Whoops 🫠
> Fix "mdbook-lintcheck" typo

- .github/workflows/ci.yml
- .github/workflows/docs.yml
Whoops, I broke our website by introducing the linkcheck `mdbook` backend in #436! This PR fixes it (see the commit description) and also improves the names of some things in our CI.
> Fix website 404

- docs/src/linter/index.md
Instead of linking to: https://thebevyflock.github.io/bevy_cli/api/bevy_lint/ we should link to: https://thebevyflock.github.io/bevy_cli/api/bevy_lint/lints/index.html
> Link directly to `all lints`

- CHANGELOG.md
- MIGRATION.md
- bevy_lint/CHANGELOG.md
- bevy_lint/MIGRATION.md
- docs/src/SUMMARY.md
- docs/src/cli/changelog.md
- docs/src/cli/migration.md
- docs/src/contribute/cli/release.md
- docs/src/contribute/linter/how-to/release.md
- docs/src/linter/changelog.md
- docs/src/linter/migration.md
This proposes a process for releasing the CLI, based it off of the linter release guide. Some noticeable points:
1. Releasing the CLI requires Bevy engine maintainer approval.
- This smooths migration for when the CLI becomes an official Bevy tool, since it will become required then.
2. The Github release description looks very similar [to the linter's](https://github.com/TheBevyFlock/bevy_cli/releases/tag/lint-v0.3.0). This is good for consistency, but may be confusing and hard to tell the difference between the two. Any ideas on how to differentiate them further?
> Write guide on releasing the CLI

- Cargo.lock
- Cargo.toml
- src/bin_target.rs
- src/config.rs
- src/external_cli/cargo/metadata.rs
- src/external_cli/mod.rs
- src/external_cli/wasm_bindgen.rs
- src/web/build.rs
- src/web/bundle.rs
- src/web/profiles.rs
- src/web/run.rs
While working on #467 I was missing the `resolve` fields and noticed that we implemented all the `cargo metadata` logic ourselves. We already use [`cargo_metadta`](https://crates.io/crates/cargo_metadata) for the `cargo` lints, so I think it makes sense also to use it for the CLI.
Tested the different apps in: https://github.com/TimJentzsch/bevy_complex_repo
> Switch to `cargo_metadata` crate.

- src/run/args.rs
- src/web/run.rs
- src/web/serve.rs
Added a host argument to allow a different address to be specified to host the web server.
This allows for setting the address to something like 0.0.0.0 to allow connections from all hosts. Or specifying the device's address on a VPN. 
Also changed how we were declaring the address and URL to be displayed to the user to allow for support of IPv6 addresses.
> Added a 'host' argument for 'bevy run web'

- MIGRATION.md
- src/build/args.rs
- src/external_cli/cargo/mod.rs
- src/run/args.rs
Fixes #471.
The changes the behavior of the `--no-default-features` flag. Before it required a value to be passed:
```sh
bevy build --no-default-features true
bevy build --no-default-features false
```
Now the flag is a toggle:
```sh
bevy build --no-default-features
bevy build
```
This is a breaking change, as passing `true` or `false` is no longer recognized.
> Make `--no-default-features` be a toggle instead of option

- README.md
- bevy_lint/README.md
- docs/src/cli/install.md
- docs/src/contribute/cli/release.md
- docs/src/contribute/linter/how-to/release.md
- docs/src/linter/install.md
This makes it so users getting started can copy-paste the installation commands necessary for both the CLI and the linter, easing onboarding. I also added an extra step in the release checklist so that these values get updated every release, so they don't fall behind.
Addresses [this comment on Discord](https://discord.com/channels/691052431525675048/1278871953721262090/1380381197930074232).
> Make install commands copy-pasteable

- bevy_lint/src/lints/cargo.rs
- bevy_lint/src/lints/nursery/duplicate_bevy_dependencies.rs
- bevy_lint/src/lints/nursery/zst_query.rs
- bevy_lint/src/lints/pedantic/borrowed_reborrowable.rs
- bevy_lint/src/lints/pedantic/main_return_without_appexit.rs
- bevy_lint/src/lints/restriction/missing_reflect.rs
- bevy_lint/src/lints/restriction/panicking_methods.rs
- bevy_lint/src/lints/style/unconventional_naming.rs
- bevy_lint/src/lints/suspicious/insert_event_resource.rs
- bevy_lint/src/lints/suspicious/insert_unit_bundle.rs
- bevy_lint/src/lints/suspicious/iter_current_update_events.rs
Right now the lint static and lint pass type are visible in the documentation:
This originally was because these items had extra documentation useful to users. Since that's no longer the case, and these items now have no documentation, they can be made `pub(crate)` and hidden from the docs.
> Make lint items `pub(crate)`, hiding them from docs

- src/web/bundle.rs
Closes #440.
We allow the user to provide custom web assets to fully control how the Bevy app is loaded.
However, it's currently only possible to provide the `web` folder for the whole workspace, providing custom assets for an individual package doesn't work.
Search for the web folder first at the package level, then the workspace level.
The [bevy_complex_repo](https://github.com/TimJentzsch/bevy_complex_repo) `workspace` folder has a `custom_web_folder` package where this can be tested.
Run `bevy run -p custom_web_folder web` in the `workspace` folder, with the CLI installed from this branch.
In the logs you should see that it's using the package-level web assets. The app itself should have an added "bevy" test in the HTML
The user might also want to customize the name of the folder / …
> Allow custom web assets to be defined at package level

- bevy_lint/src/lints/style/unconventional_naming.rs
- bevy_lint/tests/ui/unconventional_naming/plugin.rs
- bevy_lint/tests/ui/unconventional_naming/plugin.stderr
- bevy_lint/tests/ui/unconventional_naming/spoofed_name.rs
- bevy_lint/tests/ui/unconventional_naming/spoofed_name.stderr
- bevy_lint/tests/ui/unconventional_naming/system_set.rs
- bevy_lint/tests/ui/unconventional_naming/system_set.stderr
Closes #393.
This PR makes two separate improvements to the `unconventional_naming` lint. The first commit makes the lint suggestion smarter when encountering alternate plugin naming conventions:
The lint now correctly detects the `PluginFoo` and `FooPlugins` conventions, and correctly suggests the new name. No more `PluginFooPlugin`! 🪄
The second commit shrinks the amount of diagnostics we print per lint warning. Before, we were printing the plugin / system set definition twice! (The red box in the image.) There's no need to print it more than once, so this commit switches from `span_note()` to just `note()`. It also switches from carets `` ` `` to quotes `"` when printing the desired suffix, as it's text and not code.
> Make `unconventional_naming` lint smarter 🧑‍🎓🍎🧠

- bevy_lint/src/bin/main.rs
- docs/src/SUMMARY.md
- docs/src/linter/environmental-variables.md
- docs/src/linter/install.md
Closes #338 and closes #336!
`bevy_lint` requires a custom nightly Rust toolchain, and it by default assumes that you have it installed through Rustup. This is an issue for users who don't have Rustup or prefer something else (such as Nix).
This PR makes it possible to support alternative toolchain installation methods. If you set `BEVY_LINT_SYSROOT` to the path to the toolchain folder (known as the sysroot), the linter will use that instead of going through Rustup.
```
cargo install --git https://github.com/TheBevyFlock/bevy_cli --branch linter-sysroot-var --locked bevy_lint
bevy_lint
BEVY_LINT_SYSROOT="/Users/username/.rustup/toolchains/nightly-2025-04-03-TARGET" bevy_lint
```
Using a custom sysroot will need testing on all of our supported platforms, since there's some …
> Support custom linter sysroot

- .github/workflows/linter-action.yml
- bevy_lint/action.yml
- docs/src/contribute/linter/how-to/release.md
- docs/src/contribute/linter/how-to/upgrade-rust-toolchain.md
The [Github Action we provide for the linter](https://thebevyflock.github.io/bevy_cli/linter/github-actions.html) isn't great. It works well for installing from a release or from `main`, but breaks down when installing a specific commit. This is because we currently hardcode values in `action.yml`:
https://github.com/TheBevyFlock/bevy_cli/blob/ff8d39aba29f6f04aecd7f8ec429d173649646ee/bevy_lint/action.yml#L18-L19
https://github.com/TheBevyFlock/bevy_cli/blob/ff8d39aba29f6f04aecd7f8ec429d173649646ee/bevy_lint/action.yml#L25-L31
This is an extra maintenance burden that we shouldn't have to do! If the user wants to install a specific commit of the linter, it should work as expected instead of installing the `main` branch:
```yml
- name: Install `bevy_lint`
uses: …
```
> Make linter action more ergonomic

- bevy_lint/Cargo.toml
- bevy_lint/src/bin/bevy_lint.rs
- bevy_lint/src/bin/bevy_lint_driver.rs
This is a small change that makes it more clear which file in `bevy_lint/src/bin` compiles to which executable. It also shrinks the linter's `Cargo.toml`, which is a nice bonus!
> Rename linter binary sources to their executable names

- bevy_lint/action.yml
- rust-toolchain.toml
Fixes #510.
This PR modifies `bevy_lint`'s action to use Regex to capture the toolchain channel in `rust-toolchain.toml`. Specifically, it uses this pattern:
```regex
^channel = "(.+)"$
```
I recommend [looking at this in Regex101](https://regex101.com/r/zIQPCg/1) to understand what its doing. In short, it looks for the line `channel = "..."` and captures everything between the double quotes.
Additionally, I switched the toolchain components to be completely hard-coded within the action. As these components are unlikely to ever change, I figured it was far simpler than trying to use _more_ Regex to extract them from `rust-toolchain.toml`. This can be changed in the future!
> Use Regex instead of `taplo` to extract channel in linter action

- Cargo.lock
- bevy_lint/CHANGELOG.md
- bevy_lint/Cargo.toml
- bevy_lint/MIGRATION.md
- bevy_lint/README.md
- docs/src/linter/compatibility.md
- docs/src/linter/github-actions.md
- docs/src/linter/install.md
- src/commands/lint.rs
It's been just about 4 months since we released v0.3.0 of the linter, and there are several new features and useful changes that have been introduced since then! Additionally, with Bevy 0.17 heading towards the release track, we thought it best to release these features now so existing users can benefit from them.
- [Changelog](https://github.com/TheBevyFlock/bevy_cli/blob/release-v0.4.0/bevy_lint/CHANGELOG.md)
- [All Changes](https://github.com/TheBevyFlock/bevy_cli/compare/lint-v0.3.0...release-v0.4.0) (also includes changes to the CLI)
- [Migration Guide](https://github.com/TheBevyFlock/bevy_cli/blob/release-v0.4.0/bevy_lint/MIGRATION.md)
- Linter Documentation
- [Updated, not rendered](https://github.com/TheBevyFlock/bevy_cli/tree/release-v0.4.0/docs/src/linter)
- [Out of date, …
> Release linter v0.4.0

- src/external_cli/mod.rs
Previously, when `cargo metadata` fails, you'd always get this error:
But `cargo metadata` failing can also have other causes. We also need to original error from `cargo metadata` to help the user debug the issue.
Output `stderr` when the command fails:
We currently lose the color from the command, but still a lot better than before!
> Improve error message when `cargo metadata` fails

- Cargo.lock
- bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/fail/Cargo.lock
- bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/pass/Cargo.lock
- bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/fail/Cargo.lock
- bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/pass/Cargo.lock
- tests/bevy_cli_test/Cargo.lock
I ran `cargo update` for all of our Cargo workspaces in order to make sure they're all up to date. This should close the Dependabot alerts related to the `slap` crate, such as https://github.com/TheBevyFlock/bevy_cli/security/dependabot/20!
> Bump dependencies in `Cargo.lock`

- src/config.rs
Remove `debug` output when no header is specified for the given profile, since it's more confusing. I think it's enough that we print the resolved config.
`Cargo.toml`
```toml
[package.metadata.bevy_cli.dev]
default-features = false
[package.metadata.bevy_cli]
default-features = false
[package.metadata.bevy_cli.web]
default-features = false
[package.metadata.bevy_cli.web.dev]
default-features = false
```
```
❯ bevy run web -v
debug: running: `cargo metadata --format-version 1`
debug: no `headers` found in CLI metadata, using default
debug: no `headers` found in CLI metadata, using default
debug: no `headers` found in CLI metadata, using default
debug: no `headers` found in CLI metadata, using default
debug: using defaults from bevy_cli config:
features = []
default-features = false …
```
> remove log line that prints for each profile

- .github/dependabot.yml
I think the Dependabot PR's for the `cargo` lint tests are bad. It always tries to update the versions we deliberately use as "old" versions ^^
For example see: https://github.com/TheBevyFlock/bevy_cli/pull/590
> Ignore `cargo` lint projects in Dependabot

- .github/dependabot.yml
While looking over Dependabot's configuration reference, I read this:
> - For GitHub Actions, use the value `/`. Dependabot will search the `/.github/workflows` directory, as well as the `action.yml`/`action.yaml` file from the root directory.
It appears that Dependabot isn't scanning `bevy_lint/action.yml`, since it's not in the root directory. This PR corrects this by telling Dependabot to also scan the `bevy_lint` folder for Github Actions.
> Check `bevy_lint/action.yml` with Dependabot

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/src/contribute/cli/release.md
As per the [release process](https://thebevyflock.github.io/bevy_cli/contribute/cli/release.html#post-release), this PR undoes the feature-freeze and prepares the repo for more development on the CLI.
Additionally, I updated the template used for [the Github Releases](https://github.com/TheBevyFlock/bevy_cli/releases) to reflect modifications I made in the v0.1.0-alpha.2 description.
> Post-release CLI v0.1.0-alpha.2

- src/commands/lint/mod.rs
- src/web/build.rs
- src/web/getrandom.rs
Fixes #612!
I copied the changes made in #547 to `web/build.rs` over to `lint/mod.rs`, so they should now behave the same. I also modified `apply_getrandom_backend()` to take a `CargoCommonArgs` instead of a `BuildArgs`, since the linter doesn't have a `BuildArgs` (it has `LintArgs` instead).
I tested this on `bevy_new_2d`, and `bevy lint web` now compiles! :)
> Enable `getrandom` backend with `bevy lint web`

- assets/web/index.html
I find the focus ring distracting and redundant since the canvas is the only focusable element.
> Hide focus ring on canvas

- README.md
- docs/src/cli/quick-start.md
If you've previously installed bevy_cli and the linter, you need to manually update it for new installs, especially if Bevy has done a release and bumped the msrv
This is the error you get for an out of date linter:
```
❯ bevy lint
error: rustc 1.86.0-nightly is not supported by the following packages:
bevy@0.17.0-rc.1 requires rustc 1.88.0
bevy_skein@0.3.0-rc.1 requires rustc 1.88.0
sysinfo@0.37.0 requires rustc 1.88
Either upgrade rustc or select compatible dependency versions with
`cargo update <name>@<current-ver> --precise <compatible-ver>`
where `<compatible-ver>` is the latest version supporting rustc 1.86.0-nightly
Check failed: exit status: 101.
error: command `bevy_lint --profile dev` exited with status code exit status: 101
```
PR modifies readme to show a note
> add bevy lint install instructions
